version: '3.3'
services:
   db:
     image: mysql:5.7
     volumes:
       - db_vol:/var/lib/mysql
       - ./mysql-dump:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: patata23
       MYSQL_USER: root
       MYSQL_PASSWORD: patata23
     ports:
       - 3306:3306
   phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: patata23
   web:
    build:
      context: .
    depends_on:
      - db
    image: tomcat
    volumes:
            - ./ProyectoCasino.war
    ports:
      - '8080:8080'
    environment:
      MYSQL_ROOT_PASSWORD: patata23
      MYSQL_USER: root
      MYSQL_PASSWORD: patata23
volumes:
    db_vol:
